services:
  - type: web
    name: chatbot-lavanderia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn script:app
    envVars:
      - key: FLASK_APP
        value: script.py
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: FLASK_SECRET_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false 